#!/bin/bash
sudo mount /dev/nvme0n1p1 /boot/EFI

curl -s https://raw.githubusercontent.com/linux-surface/linux-surface/master/pkg/keys/surface.asc | sudo pacman-key --add -
    
sudo pacman-key --finger 56C464BAAC421453
sudo pacman-key --lsign-key 56C464BAAC421453

sudo curl https://raw.githubusercontent.com/BennyOe/arch_install/main/surfacePacman.conf -o /etc/pacman.conf

sudo pacman -Syu
sudo pacman -S linux-surface linux-surface-headers iptsd
sudo systemctl enable iptsd

sudo grub-mkconfig -o /boot/grub/grub.cfg
