#!/bin/bash

#### TODO ####
# bluetooth

#################
#### Welcome ####
#################
bootstrapper_dialog --title "Welcome" --msgbox "Welcome to the Apps Installation.\n" 6 60
dialog --stdout --msgbox "Welcome to the Apps installation.\nThis script will install additional Applications" 0 0

##################
### User Input ###
##################
# app folder
appfolder=$(dialog --stdout --inputbox "Enter additional apps" 0 0) || exit 1
clear

yay -S --noconfirm $appfolder
clear
printf "Installing user apps"
sleep 2
##################
## Standard Apps #
##################
clear
printf "Installing standard apps"
sleep 2
yay -S --noconfirm ranger redshift autorandr thunar numlockx zathura htop neofetch

##################
## Lightdm #######
##################


##################
###### ZSH #######
##################
clear
printf "Installing zsh"
sleep 2

# oh my zsh
yes | sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

# powerlevel 10k
yay -S --noconfirm zsh-theme-powerlevel10k-git
echo 'source /usr/share/zsh-theme-powerlevel10k/powerlevel10k.zsh-theme' >>~/.zshrc

# lsd
sudo pacman -S --noconfirm lsd

# zsh autosuggestions
git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions

# zsh syntax highlighting
git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting

# changing shell to zsh
sudo chsh -s $(which zsh) $(users)

# setting zsh profile
cp ~/.bash_profile ~/.zprofile

##################
###### VIM #######
##################
clear
printf "Installing vim"
sleep 2

yay -S --noconfirm neovim-nightly-bin

#Vim-Plug
sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs \
       https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'

##################
##### Spotify ####
##################

##################
#### Dot Files ###
##################
clear
printf "Installing dot files"
sleep 2

git clone https://github.com/BennyOe/.dotfiles ~/.dotfiles

##################
#### Symlinks ####
##################
chmod +x ~/.dotfiles/setsymlinks.sh
source ~/.dotfiles/symlinks.sh

clear
printf "Installation finished.\n"
printf "rebooting the system.\n"
printf "press a key to continue...\n"
read < /dev/tty
reboot


